In [28]:
import numpy as np

In [49]:
# đọc dữ liệu từ file
ratings = np.loadtxt("ratings.txt", dtype = int)
print("ratings: \n", ratings)

# số user, số movies
num_users = ratings.shape[0]
num_movies = ratings.shape[1]

print("num_users: ", num_users)
print("num_movies: ", num_movies)

ratings: 
 [[3 0 4 ... 1 1 3]
 [3 2 4 ... 1 1 1]
 [1 4 0 ... 0 4 4]
 ...
 [1 3 4 ... 0 0 4]
 [1 4 1 ... 0 2 5]
 [5 3 1 ... 0 0 0]]
num_users:  501
num_movies:  100


In [50]:
# hàm chuẩn hóa dữ liệu
def normalize_ratings(ratings):
    num_movies = ratings.shape[1]

    ratings_mean = np.zeros(shape = (1, num_movies))
    ratings_norm = np.zeros(shape = ratings.shape)

    for i in range(num_movies):
        # lấy ra các giá trị khác 0
        idx = ratings[:, i] > 0
        # tính mean của các giá trị khác 0
        ratings_mean[0, i] = np.mean(ratings[idx, i])
        # chuẩn hóa dữ liệu
        ratings_norm[idx, i] = ratings[idx, i] - ratings_mean[0, i]

    return ratings_norm, ratings_mean


In [51]:
# chuẩn hóa dữ liệu
ratings, ratings_mean = normalize_ratings(ratings)
print("ratings after normalize: \n", ratings)

ratings after normalize: 
 [[ 0.06161137  0.          1.08196721 ... -1.9451074  -2.01187648
  -0.16428571]
 [ 0.06161137 -1.00472813  1.08196721 ... -1.9451074  -2.01187648
  -2.16428571]
 [-1.93838863  0.99527187  0.         ...  0.          0.98812352
   0.83571429]
 ...
 [-1.93838863 -0.00472813  1.08196721 ...  0.          0.
   0.83571429]
 [-1.93838863  0.99527187 -1.91803279 ...  0.         -1.01187648
   1.83571429]
 [ 2.06161137 -0.00472813 -1.91803279 ...  0.          0.
   0.        ]]


In [52]:

# đọc dữ liệu từ file
user_features = np.loadtxt("user_features.txt")
movie_features = np.loadtxt("movie_features.txt")

print("user_features: \n", user_features)
print("movie_features: \n", movie_features)

user_features: 
 [[-0.1  0.3  0.7 ... -0.9 -1.1  1.2]
 [ 0.6  1.3  0.8 ...  0.7 -0.9  0.8]
 [ 0.3 -0.6 -0.9 ...  0.3 -0.1  1.2]
 ...
 [-0.7  0.3  0.2 ...  0.6  0.1 -0.9]
 [-0.8  1.1 -0.3 ...  0.4  0.1 -0.4]
 [-1.1 -0.4 -0.3 ... -0.2 -0.4 -0.3]]
movie_features: 
 [[ 0.3 -0.4  1.7 -1.2  0.2 -1.1  1.8  0.9 -1.7  2.3]
 [ 0.3 -0.4 -0.3  0.2  0.7 -0.4 -0.8 -0.6 -0.3  0.3]
 [-0.9 -0.5  1.3  0.5  0.1  2.7 -2.3  0.5  1.3 -0.5]
 [ 1.1  0.5 -0.4 -0.7  1.   0.3 -0.5 -0.7 -0.8 -0.6]
 [ 1.  -0.5 -1.7 -0.8  0.4  1.4 -0.3 -1.2  0.7  1. ]
 [ 1.1  0.7  0.4  0.7  1.3 -0.  -1.   1.1  1.6 -2. ]
 [ 0.8 -0.6 -0.3  1.2 -1.2 -1.2 -0.4  1.3 -0.3 -1.8]
 [ 0.5  1.1  0.6 -0.5 -0.4 -0.3  0.4 -0.  -0.3 -2.3]
 [-1.   1.9 -1.3  0.8 -0.3  0.   1.8  0.7 -0.3  1.1]
 [ 0.5  0.7 -0.9  2.4  1.4  2.  -0.6  2.3  0.9 -1.2]
 [-1.5 -0.2 -0.7 -0.1 -0.1 -1.   1.1  1.6  0.2  1.4]
 [-0.   0.6 -0.3 -1.  -0.8 -1.9 -1.1  0.3 -0.5 -2.3]
 [-1.1  0.9 -0.1  1.1  1.7  0.7 -0.1  0.   0.3  0.3]
 [-0.5  0.3 -0.5 -0.3  0.2 -0.8  2.4  0.2  1.5 -

In [53]:
# hàm tính loss function 
def calc_lost(user_features, movie_features, ratings):

    # ma trận : 1 - 0 | 1 nếu đánh giá, 0 nếu chưa đánh giá
    mask = (ratings != 0) * 1

    # số lượng đánh giá
    count = 0
    for i in range(ratings.shape[0]):
        for j in range(ratings.shape[1]):
            if ratings[i, j] != 0:
                count += 1

    # tính giá trị dự đoán
    predicted = np.dot(user_features, movie_features.T)

    # tính hàm mất mát
    lost = np.sum(np.square(mask * (predicted - ratings)))

    return lost/count

In [54]:
# hàm gradient descent
def gradient_descent(user_features, movie_features, ratings, learning_rate, num_iterations):
    # ma trận did_rate có giá trị 1 tại các vị trí có ratings > 0, ngược lại là 0
    did_rate = (ratings != 0) * 1
    # print("did_rate: \n", did_rate)

    # số đánh giá
    numRated = 0
    for i in range(did_rate.shape[0]):
        for j in range(did_rate.shape[1]):
            if did_rate[i, j] == 1:
                numRated += 1

    # lặp lại quá trình gradient descent
    for i in range(num_iterations):
        # tính độ lệch giữa dữ liệu thực tế và dữ liệu dự đoán
        predicted = np.dot(user_features, movie_features.T)
        # print("predicted: \n", predicted)
        difference = (ratings - predicted) * did_rate
        # print("difference: \n", difference)

        # tính gradient  cho user_features và movie_features
        user_features_grad = -2/(numRated) * np.dot(difference, movie_features) 
        movie_features_grad = -2/(numRated) * np.dot(difference.T, user_features)



        # cập nhật user_features và movie_features
        user_features -= learning_rate * user_features_grad
        movie_features -= learning_rate * movie_features_grad

        # tính giá trị hàm mất mát
        error = calc_lost(user_features, movie_features, ratings)

        if error < 1.7:
            print("iteration: ", i, "error: ", error)

        # chỉnh lại learning_rate
        # if error < 1.6:
        #     learning_rate = 1
            
     

        # nếu error < 0.001 thì dừng quá trình gradient descent
        if error < 0.001:
            print("iteration: ", i, "error: ", error)
            break

    return user_features, movie_features

In [55]:
# thiết lập các tham số cho gradient descent
learning_rate = 100
num_iterations = 1000

# thực hiện gradient descent
users_features, movie_features = gradient_descent(user_features, movie_features, ratings, learning_rate, num_iterations)


iteration:  31 error:  1.699635165463006
iteration:  32 error:  1.6952340445297933
iteration:  33 error:  1.6910004009674722
iteration:  34 error:  1.6869272271931053
iteration:  35 error:  1.683008171994813
iteration:  36 error:  1.6792374607610172
iteration:  37 error:  1.6756098132652275
iteration:  38 error:  1.6721203632370996
iteration:  39 error:  1.6687645829045437
iteration:  40 error:  1.665538214720269
iteration:  41 error:  1.6624372116281674
iteration:  42 error:  1.6594576865017747
iteration:  43 error:  1.6565958708058979
iteration:  44 error:  1.6538480820903714
iteration:  45 error:  1.6512106996111275
iteration:  46 error:  1.6486801471729433
iteration:  47 error:  1.6462528821822857
iteration:  48 error:  1.6439253898687733
iteration:  49 error:  1.6416941816615445
iteration:  50 error:  1.6395557967755814
iteration:  51 error:  1.6375068061581757
iteration:  52 error:  1.635543818055175
iteration:  53 error:  1.6336634845709268
iteration:  54 error:  1.6318625087079

In [56]:
# in ra các ma trận đặc trưng của người dùng và movies
print("user features: \n", user_features)
# print("\n")
print("movie features: \n", movie_features)

# ghi dữ liệu vào file
np.savetxt("user_features_output.txt", user_features, fmt = "%.1f")
np.savetxt("movie_features_output.txt", movie_features, fmt = "%.1f")

user features: 
 [[ 0.39822651  0.33860525 -0.62043345 ...  0.66669553  0.4695065
   0.6521495 ]
 [ 0.22560416  0.74399593  0.77952838 ...  0.3485387   0.22177801
   0.47145473]
 [ 0.50452977  0.0906462   0.04473535 ...  0.05467145  0.48057645
   0.02175745]
 ...
 [ 0.32851792 -0.3254661   0.65157613 ... -0.07732889  1.34996348
   0.14236459]
 [ 0.09638411 -0.58295264 -0.08246864 ... -0.92240652 -0.99829104
   0.26949858]
 [-3.34788351  0.66092066  0.63519015 ... -0.4530687   0.5748496
   0.35516168]]
movie features: 
 [[-4.29969298e-01  1.08108870e+00 -6.53862720e-01  1.05965708e+00
  -1.02659578e-01  3.67327936e-01  4.85675848e-01 -8.75323838e-02
   7.34898346e-01 -5.55617075e-02]
 [ 1.91700545e-01 -3.37226050e-01 -9.35827964e-02  3.11602686e-01
  -3.71165012e-01  2.98710810e-02 -1.59772801e-01 -6.56307122e-01
   3.11976272e-01  3.46185198e-01]
 [ 3.85024828e-01  2.70890161e-01 -9.04695953e-01 -3.80844586e-02
   8.32261178e-01  3.01039133e-02 -8.90069756e-02  6.47036846e-03
   2.4123

In [57]:
# bảng đánh giá dự đoán 
predicted_ratings = np.dot(user_features, movie_features.T) + ratings_mean
print("predicted ratings: \n", predicted_ratings)

# ghi dữ liệu vào file, làm tròn 1 chữ số thập phân
np.savetxt("prediction.txt", predicted_ratings, fmt = "%.1f")

predicted ratings: 
 [[2.99689634 3.03616591 3.23127565 ... 2.18348443 2.53412788 3.47143732]
 [3.08910701 2.64127218 2.59617923 ... 2.66336091 3.08927597 3.16208921]
 [3.12538292 2.80674782 3.38981896 ... 2.39373421 3.38299522 2.34479394]
 ...
 [2.28961633 3.41952169 3.10003119 ... 2.74894645 3.95549201 4.31173881]
 [1.68061402 3.60429769 2.45681935 ... 2.95230798 3.16308527 3.94403361]
 [5.00364966 2.98159139 1.05909381 ... 4.70170393 0.6778597  9.73871088]]


In [58]:
# dự đoán của người dùng mới
my_predictions = predicted_ratings[-1, :]
print("my predictions: \n", my_predictions)


my predictions: 
 [ 5.00364966  2.98159139  1.05909381  2.04601926  2.00674031  5.26121568
  4.21975579 -3.87749561  2.24348489  4.0970405   2.06499744  5.68661949
  0.92479938  2.92211844  2.25566239  3.87545389  5.21164425  5.55628054
  5.0919147   2.94138862  5.92447705  2.635147   -1.72191473  4.42192252
  4.57563079 -0.66993267  2.11844178  7.5684769   5.06467631  7.80026811
  5.7028568   3.6306614   0.19624952  6.46286637  0.91957934  6.1533027
  1.9518217   7.20820151  3.75264737  3.95580922  3.06557671  5.11395958
  1.50275148 -1.78542685  3.00044506 -0.55138155  2.1044662   3.96419175
 -0.08008458  2.83969701  2.52713023  2.74926973  0.6092581   0.93443174
 -0.58952134  2.31660308  1.7915717   0.95649376  5.0007188   1.17431711
  2.12517872  5.76863925  7.71458099  3.29218379  3.15486082  6.03049541
  3.7963922  -1.0847156  -0.92821582  3.62827365  0.35336009  5.11327011
  1.75578842  1.5675998   5.56588782 -2.0760598  -1.16648606 -5.19354134
  3.74162934 -4.19825262  3.589191