In [1]:
import numpy as np

In [3]:
# # Tạo dữ liệu mẫu: số hàng = số người, số cột = số movies
# kích thước của ma trận đánh giá
num_users, num_movies = (500, 100)


# Tạo ma trận ngẫu nhiên các giá trị từ 0 đến 5
ratings = np.random.randint(6, size = (num_users, num_movies))

# hàm shape trả về bộ (m, n) với m là số hàng, n là số cột
# shape[0] là số hàng, shape[1] là số cột
ratings.shape
print("ratings: \n", ratings)

# ma trận cho người dùng mới chỉ mới đánh giá 3 bộ phim
new_user_ratings = np.zeros((1, num_movies))
new_user_ratings[0, 0] = 5
new_user_ratings[0, 1] = 3
new_user_ratings[0, 2] = 1
print("new user rating: \n",new_user_ratings)


# thêm new_user_ratings vào ratings
ratings = np.vstack([ratings, new_user_ratings])
print("ratings after append: \n", ratings)

# ghi dữ liệu vào file
np.savetxt("ratings.txt", ratings, fmt = "%d")


ratings: 
 [[3 0 4 ... 1 1 3]
 [3 2 4 ... 1 1 1]
 [1 4 0 ... 0 4 4]
 ...
 [3 5 4 ... 1 4 0]
 [1 3 4 ... 0 0 4]
 [1 4 1 ... 0 2 5]]
new user rating: 
 [[5. 3. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]
ratings after append: 
 [[3. 0. 4. ... 1. 1. 3.]
 [3. 2. 4. ... 1. 1. 1.]
 [1. 4. 0. ... 0. 4. 4.]
 ...
 [1. 3. 4. ... 0. 0. 4.]
 [1. 4. 1. ... 0. 2. 5.]
 [5. 3. 1. ... 0. 0. 0.]]


In [1]:
import numpy as np

# giả sử features = 10 (số lượng đặc trưng)
num_features = 10
num_users, num_movies = (501, 100)

# Hàm random.randn() trả về các giá trị ngẫu nhiên trong khoảng từ 0 đến 1
# Khởi tạo ma trận đặc trưng của người dùng 
user_features = np.random.randn(num_users, num_features) 
print("user features: \n", user_features)

# Khởi tạo ma trận đặc trưng của movies
movie_features = np.random.randn(num_movies, num_features)
print("movie features: \n", movie_features)

# ghi dữ liệu vào file
np.savetxt("user_features.txt", user_features, fmt = "%.1f")
np.savetxt("movie_features.txt", movie_features, fmt = "%.1f")

user features: 
 [[-0.09835891  0.26113897  0.65364122 ... -0.86144026 -1.12636701
   1.22303721]
 [ 0.60292175  1.30028003  0.7741115  ...  0.65050483 -0.94326439
   0.77765369]
 [ 0.26021352 -0.62465738 -0.93036007 ...  0.34152486 -0.11943438
   1.15131066]
 ...
 [-0.74163375  0.27670686  0.19241586 ...  0.55889098  0.13923044
  -0.94307417]
 [-0.8003184   1.05939685 -0.27362749 ...  0.42318634  0.05636894
  -0.35719657]
 [-1.08206342 -0.42785737 -0.29151339 ... -0.21987682 -0.44337823
  -0.29011213]]
movie features: 
 [[ 2.81922300e-01 -4.05775568e-01  1.70048066e+00 -1.22274132e+00
   2.27738002e-01 -1.07997948e+00  1.76543026e+00  8.80427411e-01
  -1.69228164e+00  2.31010349e+00]
 [ 3.28984358e-01 -4.24175861e-01 -3.11746006e-01  1.92137767e-01
   6.56587930e-01 -3.73004422e-01 -8.41260505e-01 -6.35352680e-01
  -3.40085455e-01  3.13649906e-01]
 [-8.61207268e-01 -5.31995746e-01  1.27069357e+00  5.31251441e-01
   9.11654613e-02  2.68800790e+00 -2.29554134e+00  4.89524542e-01
   1.30